apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "plex-simple.fullname" . }}
  labels:
    {{- include "plex-simple.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  hostNetwork: true
  selector:
    matchLabels:
      {{- include "plex-simple.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "plex-simple.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "plex-simple.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 32400
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      volumes:

        - name: database-{{ include "plex-simple.fullname" . }}
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: database-{{ include "plex-simple.fullname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}

       - name: transcode-{{ include "plex-simple.fullname" . }}
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: transcode-{{ include "plex-simple.fullname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}

       - name: media-{{ include "plex-simple.fullname" . }}
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: media-{{ include "plex-simple.fullname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
