{{- if and .Values.databasePersistence.enabled (not .Values.databasePersistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    {{- include "plex-simple.labels" . | nindent 4 }}
  name: database-{{ include "plex-simple.fullname" . }}
spec:
  accessModes:
  {{- range .Values.databasePersistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.databasePersistence.size | quote }}
  {{ include "plex-simple.databaseStorageClass" . }}
{{- end }}