{{- if and .Values.transcode-persistence.enabled (not .Values.transcode-persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    {{- include "plex-simple.labels" . | nindent 4 }}
  name: transcode-{{ include "plex-simple.fullname" . }}
spec:
  accessModes:
  {{- range .Values.transcode-persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.transcode-persistence.size | quote }}
  {{ include "plex-simple.transcode-storageClass" . }}
{{- end }}