{{- if and .Values.transcodePersistence.enabled (not .Values.transcodePersistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    {{- include "plex-simple.labels" . | nindent 4 }}
  name: transcode-{{ include "plex-simple.fullname" . }}
spec:
  accessModes:
  {{- range .Values.transcodePersistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.transcodePersistence.size | quote }}
  {{ include "plex-simple.transcodeStorageClass" . }}
{{- end }}